### ISSUE TITLE
[Bug] Custom colours doesn't set back on restart

### ISSUE THREAD

**Issue by HeySora** [sll552/CorsairLED-MB-Plugin#13]
**Describe the bug**
When MusicBee is started and a configuration file already exists, the colors are not being taken back from the config. They are not even resetted to red/black. They just seem transparent.
That only applies to custom hexadecimal colors. e.g. `BackgroundColor=Teal` will work, but `BackgroundColor="#008080"` won't work.

The issue is that the foreground effect (e.g. rainbow gradient) will still appear, but it will only grow. It never shrinks itself, probably because the plugin is trying to clear all the colors with a transparent color for each update.

**To Reproduce**
1. Go to the settings of the plugin
2. Set some colors, and save.
3. Everything will work. Close MusicBee and re-open it.
4. The RGB lighting won't work, as described above.

**Expected behavior**
The colors should restore without issues.

**Screenshots**
![Settings window](https://i.heysora.net/TCENuE.png)

**Environment (please complete the following information):**
 - MusicBee Version: [e.g. 3.3.7310]
 - Plugin Version: v1.0.3

**Additional context**
I'm using the rainbow gradient for the foreground color. I have a K95 RGB Platinium Keyboard, as shown in the screenshot.

For bypassing this issue, I have to manually reset the colors to the ones I want each time I start MusicBee. The RGB lighting will work again.

CorsairLED.settings is succesfully written, and contains the colors I've set. The error seems to occur on the plugin initialization.
![CorsairLED.settings contents](https://i.heysora.net/oFW0jg.png)

When using some C# native colors, everything works fine!
![Working CorsairLED.settings](https://i.heysora.net/3YwmbR.png)

**Comment by sll552** [comment]
I have reproduced the issue, the problem is that the color string is quoted in the config file. This is done by the library I use for the configuration so I need to do a little more digging to fix this.

**Comment by sll552** [comment]
Should be fixed in v1.0.4 https://github.com/sll552/CorsairLED-MB-Plugin/releases/tag/v1.0.4.

You will need to recreate and save your config one last time 😉
